@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\Ki\Documents\Projects\devious better launcher\DeviousClientLauncher.exe
REM BFCPEICON=C:\Users\Ki\Documents\Projects\devious better launcher\devious.ico
REM BFCPEICONINDEX=3
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=1
REM BFCPEVERINCLUDE=0
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=Product Name
REM BFCPEVERDESC=Product Description
REM BFCPEVERCOMPANY=Your Company
REM BFCPEVERCOPYRIGHT=Copyright Info
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=25
REM BFCPEWINDOWWIDTH=80
REM BFCPEWTITLE=Devious Launcher
REM BFCPEOPTIONEND
@echo off

set "JAVA_HOME=%cd%\jre"

set "PATH=%JAVA_HOME%\bin;%PATH%"

java -jar devious-client-launcher.jar
